=== Mossyfruit/proyectoLMT/kakapo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="pagina">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="lista"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="lista">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="fechaContribucion"/>
                    <xs:element ref="nombre"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="fechaContribucion">
        <xs:complexType>
            <xs:attribute name="aÃ±o" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string"/>
</xs:schema>

=== Mossyfruit/proyectoLMT/kakapo2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="kakapo.xsl"?>
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/1DAM%26%261DAW/Desktop/trabajo/kakapo/kakapo.xsd">
	<lista>
		<titulo>Consultores</titulo>
		<nombre>Jose Javier "JJ"</nombre>
		<fechaContribucion año="2023"/>
		<nombre>Sergio "Sokoh"</nombre>
		<fechaContribucion año="2023"/>
		<nombre>Raquel "RachelDLG"</nombre>
		<fechaContribucion año="2019"/>
	</lista>
	<lista>
		<titulo>Cuidadores de Kakapo</titulo>
		<nombre>Silvia "KeiKei"</nombre>
		<nombre>Crona "Cona"</nombre>
		<nombre>Maria de la Fé de Triana "Marifé"</nombre>
	</lista>
	<lista>
		<titulo>Empresas colaboradoras</titulo>
		<nombre>Affinity Petcare SA</nombre>
		<nombre>Piensos Picart SA</nombre>
		<nombre>Asociación de Defensa de Derechos Animales</nombre>
	</lista>
</pagina>

=== Mossyfruit/proyectoLMT/kakapo.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="kakapo.xsl"?>
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/1DAM%26%261DAW/Desktop/trabajo/kakapo/kakapo.xsd">
	<lista>
		<titulo>Contribuidores</titulo>
		<nombre>Agus "Dostendite"</nombre>
		<fechaContribucion a침o="2022"/>
		<nombre>Adri "Adravii"</nombre>
		<fechaContribucion a침o="2023"/>
		<nombre>Iv치n "Moss"</nombre>
		<fechaContribucion a침o="2019"/>
	</lista>
	<lista>
		<titulo>Colaboradores</titulo>
		<nombre>Dessire "Rella"</nombre>
		<nombre>Elon "P de Paulo"</nombre>
		<nombre>John Doe</nombre>
	</lista>
	<lista>
		<titulo>Kakapos adoptados</titulo>
		<nombre>Spotty</nombre>
		<nombre>Chai</nombre>
		<nombre>Pistacho</nombre>
	</lista>
</pagina>
